# 端口号
server:
  port: 18082

# 配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchase?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 88888888

# 配置mybatis的映射地址
mybatis:
  mapper-locations: classpath:/mapping/*.xml
#  logging存放位置
logging:
  file:
    path: /Users/cuiyuhua/log
  level:
    com:
      cyh: debug
    java:
      sql: debug
